### ISSUE TITLE
Android Open and Save String to/from Google Drive SDK

### ISSUE THREAD

**Issue by achinverma** [googledrive/android-quickstart#4]
I have read allot about Google drive integration and I want to save STRING into Google drive and also to retrieve, I have used this demo please anyone provide me demo for my requirement
 i have read that, but how can i retrieve the data that i saved?	
that only saved the data to drive, is there any code to get that particular data

**Comment by kroikie** [comment]
You can use the AppData folder for storing that type of data. Consider [this][1] sample for an example of creating AppData.

[1]: https://github.com/googledrive/android-demos/blob/master/src/com/google/android/gms/drive/sample/demo/CreateFileInAppFolderActivity.java
