### ISSUE TITLE
Error: Calling connect() while still connected, missing disconnect()

### ISSUE THREAD

**Issue by BL-Lau** [googledrive/android-quickstart#6]
Thank you for your quick start sample, I was able to use the standalone app, took photo and saved to my G-drive. 

I then tried to integrate with my app and started an new activity to this class using intent. I did not make any change to the class other than the class name. The app ran, I could see the camera app and able to take picture. My G-drive "Upload to Drive" screen pops up, showing the file name, account and root folder of My Drive, I could also browse on the My Drive button and choose folders. However, when I clicked ok, the app crashed. 

The logcat record:
08-26 16:54:49.761: I/g-drive-quickstart(1566): API client connected.
08-26 16:54:49.761: I/g-drive-quickstart(1566): Creating new contents.
08-26 16:54:49.851: I/g-drive-quickstart(1566): New contents created.
08-26 16:56:58.271: E/GmsClient(1566): Calling connect() while still connected, missing disconnect().
08-26 16:56:59.271: I/g-drive-quickstart(1566): API client connected.
08-26 16:56:59.271: I/g-drive-quickstart(1566): Creating new contents.
08-26 16:56:59.311: I/g-drive-quickstart(1566): New contents created.

Kindly let me know what could be the problem. Appreciate your helps.

**Comment by kroikie** [comment]
Looks like you are calling connect when you are not supposed to.

**Comment by dmitry-zaitsev** [comment]
@kroikie this is not descriptive answer. `when you are not supposed to.` - when?
